/*
 * main.c
 *
 *  Created on: 29-Nov-2022
 *      Author: harinit
 */

/*
#include<stdio.h>
#include<stdlib.h>

#define PI 3.14f
#define AREA_OF_CIRCLE(x) (PI) * (x) * (x);

int main(){
	float area_circle;
	area_circle = AREA_OF_CIRCLE(1+1);
	printf("Area %f",area_circle);
	return 0;
}

*/

/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdio.h>

//#define AREA_TRI
//#define AREA_CIR

#if !defined(AREA_TRI) && !defined(AREA_CIR)
	//#error "No macros defined"
	#warning "No macros defined"
#endif

int main()
{


//#ifdef AREA_CIR
	printf("This is circle area calculation program\n");
   float radius = 0;
   fflush(stdout);
   printf("Enter the radius :");
   fflush(stdout);
   scanf("%f", &radius);
   printf("Area of circle  = %f\n",(3.1415 * radius * radius));
   fflush(stdout);
//#endif

//#ifdef AREA_TRI
   printf("This is Triangle area calculation program\n");
   float base, height;
   fflush(stdout);
   printf("Enter base and height: ");
   fflush(stdout);
   scanf("%f%f",&base, &height);
   printf("Area of triangle = %f\n", (0.5 * base * height));

//#endif

   return 0;

}
